name: terraform-validate-ci
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-validate-ci.yaml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-validate-ci.yaml'

jobs:
  terraform-validate-ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # or your target region
        run: |
          echo "AWS credentials configured"

      - name: terraform init & validate
        run: |
          cd terraform/
          terraform init -backend=false
          terraform validate
